<script setup lang="ts">
import { computed, nextTick, reactive, ref } from "vue"; import { useRoute, useRouter } from "vue-router"; import { ElMessage, ElMessageBox } from "element-plus"; import { Delete, Edit, Promotion, Refresh, VideoPause } from "@element-plus/icons-vue"; import { queryApi } from "../api/ops"; import { streamQuery } from "../api/sse"; import { knowledgeApi } from "../api/knowledge"; import type { ChatMessage, Citation, KnowledgePreview, SessionItem } from "../types";
const route=useRoute(); const router=useRouter(); const sessions=ref<SessionItem[]>([]); const sessionId=ref(String(route.query.session||crypto.randomUUID())); const messages=ref<ChatMessage[]>([]); const question=ref(""); const sending=ref(false); const error=ref(""); const renameItem=ref<SessionItem|null>(null); const renameTitle=ref(""); const deleteItem=ref<SessionItem|null>(null); const preview=ref<KnowledgePreview|null>(null); const previewOpen=ref(false); let controller:AbortController|null=null;
async function loadSessions(){sessions.value=await queryApi.sessions()}
async function loadMessages(){if(!route.query.session)return; const rows=await queryApi.messages(sessionId.value); messages.value=rows.map(x=>({role:x.role as "user"|"assistant",content:x.content,requestId:x.request_id,citations:x.citations}))}
void loadSessions(); void loadMessages();
async function selectSession(id:string){sessionId.value=id; await router.replace({path:"/chat",query:{session:id}}); await loadMessages()}
function newSession(){sessionId.value=crypto.randomUUID();messages.value=[];void router.replace({path:"/chat"})}
async function send(text=question.value){const q=text.trim();if(!q||sending.value)return;question.value="";messages.value.push({role:"user",content:q},{role:"assistant",content:""});sending.value=true;error.value="";controller=new AbortController();let answer="";const citations:Citation[]=[];const warnings:string[]=[];try{await streamQuery(q,sessionId.value,e=>{if(e.event==="delta"){answer=String(e.data.content||"");messages.value[messages.value.length-1].content=answer}else if(e.event==="citation")citations.push(e.data as unknown as Citation);else if(e.event==="warning")warnings.push(String(e.data.message||""));else if(e.event==="error")throw new Error(String(e.data.message||"生成失败"))},controller.signal);messages.value[messages.value.length-1]={role:"assistant",content:answer,citations,warnings};await loadSessions();if(!route.query.session)await router.replace({path:"/chat",query:{session:sessionId.value}})}catch(e){error.value=e instanceof Error?e.message:"问答失败";messages.value.pop()}finally{sending.value=false;controller=null}}
async function openCitation(c:Citation){try{preview.value=await knowledgeApi.preview(c.knowledge_id,c.version_id);previewOpen.value=true}catch{ElMessage.error("引用知识已失效或无权访问")}}
async function deleteSession(){const target=deleteItem.value;if(!target)return;await queryApi.deleteSession(target.session_id);deleteItem.value=null;if(sessionId.value===target.session_id)newSession();await loadSessions()}
async function renameSession(){if(!renameItem.value)return;await queryApi.renameSession(renameItem.value.session_id,renameTitle.value);renameItem.value=null;await loadSessions()}
</script><template><div class="chat-layout"><el-card class="page-card session-side" header="历史会话"><template #header><div class="card-header"><span>历史会话</span><el-button size="small" @click="newSession">新会话</el-button></div></template><el-scrollbar height="calc(100vh - 210px)"><div v-for="item in sessions" :key="item.session_id" :class="['session-item',{active:item.session_id===sessionId}]" @click="selectSession(item.session_id)"><span class="session-title">{{ item.title||item.session_id }}</span><el-space><el-button link :icon="Edit" @click.stop="renameItem=item;renameTitle=item.title"/><el-button link type="danger" :icon="Delete" @click.stop="deleteItem=item"/></el-space></div><el-empty v-if="!sessions.length" description="暂无历史"/></el-scrollbar></el-card><el-card class="page-card chat-card"><template #header><div class="card-header"><span>AI 智能问答</span><el-tag type="primary">受权限约束的知识检索</el-tag></div></template><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="form-alert"/><el-scrollbar class="message-list"><el-empty v-if="!messages.length" description="提出一个问题，我会基于授权知识回答"><el-space direction="vertical"><el-button v-for="q in ['差旅报销需要哪些材料？','年假如何申请？','产品版本发布需要哪些检查？']" :key="q" @click="send(q)">{{q}}</el-button></el-space></el-empty><div v-for="(item,index) in messages" :key="index" :class="['message-row',item.role==='user'?'user':'assistant']"><div class="message-bubble"><span v-if="item.role==='user'">{{ item.content }}</span><template v-else><div class="markdown">{{ item.content || '正在生成...' }}</div><el-alert v-for="w in item.warnings" :key="w" :title="w" type="warning" show-icon :closable="false"/><div v-if="item.citations?.length" class="citation-list"><strong>知识来源</strong><el-card v-for="c in item.citations" :key="c.chunk_id" shadow="hover" @click="openCitation(c)"><small>{{ c.knowledge_id }} · {{ c.source }}</small><div>{{ c.content }}</div></el-card></div></template></div></div></el-scrollbar><div class="chat-composer"><el-input v-model="question" type="textarea" :rows="2" placeholder="输入问题，Ctrl + Enter 发送" @keydown.ctrl.enter.prevent="send()"/><el-button v-if="sending" :icon="VideoPause" @click="controller?.abort()">停止</el-button><el-button type="primary" :icon="Promotion" :loading="sending" @click="send()">发送</el-button></div></el-card><el-dialog v-model="renameItem" title="重命名会话"><el-input v-model="renameTitle" maxlength="255"/><template #footer><el-button @click="renameItem=null">取消</el-button><el-button type="primary" @click="renameSession">保存</el-button></template></el-dialog><el-dialog :model-value="Boolean(deleteItem)" title="删除会话" @close="deleteItem=null"><p>该会话消息和引用将一并删除，且不可恢复。</p><template #footer><el-button @click="deleteItem=null">取消</el-button><el-button type="danger" @click="deleteSession">删除</el-button></template></el-dialog><el-dialog v-model="previewOpen" :title="preview?.title||'引用知识'" width="900px"><div class="markdown">{{ preview?.markdown }}</div></el-dialog></div></template>
