<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue"; import { ElMessage } from "element-plus";
import { UploadFilled } from "@element-plus/icons-vue"; import { knowledgeApi } from "../api/knowledge"; import { importApi } from "../api/ops"; import type { ImportJob, KnowledgeUnit } from "../types";
const knowledgeId=ref(""); const units=ref<KnowledgeUnit[]>([]); const job=ref<ImportJob|null>(null); const selectedFile=ref<File|null>(null); let timer:number|undefined;
knowledgeApi.list({page:1,page_size:100,status:""}).then(r=>units.value=r.items).catch(()=>undefined);
const jobRows=computed(()=>job.value?[job.value]:[]);
async function refresh(){ if(job.value) job.value=await importApi.job(job.value.job_id); }
async function upload(){ if(!knowledgeId.value||!selectedFile.value) return ElMessage.warning("请选择知识单元和文件"); const result=await knowledgeApi.uploadVersion(knowledgeId.value,selectedFile.value) as {job_id:string}; job.value=await importApi.job(result.job_id); ElMessage.success("解析任务已提交"); }
watch(job,()=>{ if(timer) clearInterval(timer); if(job.value && !["succeeded","failed","cancelled"].includes(job.value.status)) timer=window.setInterval(()=>void refresh(),2000); });
onBeforeUnmount(()=>{if(timer)clearInterval(timer)});
</script><template><el-card class="page-card" header="文档导入"><el-alert title="文档会先进入 MinIO，再由 Worker 执行解析、图片摘要、切片、向量化和 Milvus 索引。" type="info" show-icon :closable="false" class="toolbar" /><el-select v-model="knowledgeId" filterable placeholder="选择知识单元" style="width:100%"><el-option v-for="item in units" :key="item.knowledge_id" :label="item.title+' ('+item.knowledge_id+')'" :value="item.knowledge_id" /></el-select><el-upload class="top-gap" drag :auto-upload="false" :limit="1" accept=".pdf,.doc,.docx,.md,.markdown,.txt" :on-change="(file:any)=>selectedFile=file.raw||null" :on-remove="()=>selectedFile=null"><el-icon class="el-icon--upload"><upload-filled /></el-icon><div class="el-upload__text">点击或拖拽文档到此处</div><template #tip><div class="el-upload__tip">支持 PDF、DOC、DOCX、Markdown、TXT</div></template></el-upload><el-button type="primary" class="top-gap" @click="upload">提交导入</el-button><el-divider/><el-button @click="refresh" :disabled="!job">刷新任务</el-button><el-table :data="jobRows" class="top-gap"><el-table-column prop="job_id" label="任务 ID" min-width="220" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="stage" label="阶段" width="140" /><el-table-column label="进度" width="220"><template #default="s"><el-progress :percentage="s.row.progress" /></template></el-table-column><el-table-column prop="attempts" label="重试" width="80" /><el-table-column prop="last_error" label="错误" show-overflow-tooltip /><el-table-column label="操作" width="90"><template #default="s"><el-button v-if="s.row.status==='failed'" link @click="importApi.retry(s.row.job_id).then(refresh)">重试</el-button></template></el-table-column></el-table></el-card></template>
