<script setup lang="ts">
import { reactive, ref } from "vue"; import { ElMessage } from "element-plus"; import { configurationApi } from "../api/ops"; import type { ModelConfig, SystemSetting } from "../types";
const tab=ref("models");const models=ref<ModelConfig[]>([]);const settings=ref<SystemSetting[]>([]);const modelEdit=ref<ModelConfig|null>(null);const settingEdit=ref<SystemSetting|null>(null);const modelForm=reactive({name:"",base_url:"",model_name:"",api_key:"",status:"active"});const settingForm=reactive({value:"",description:""});
async function load(){const [m,s]=await Promise.all([configurationApi.models(),configurationApi.settings()]);models.value=m;settings.value=s}void load();
function openModel(row:ModelConfig){modelEdit.value=row;Object.assign(modelForm,{name:row.name,base_url:row.base_url,model_name:row.model_name,api_key:"",status:row.status})}
async function saveModel(){if(modelEdit.value)await configurationApi.saveModel(modelEdit.value.model_type,{...modelForm,options:modelEdit.value.options});ElMessage.success("模型配置已保存，新的问答请求将立即使用该配置");modelEdit.value=null;await load()}
async function testModel(type:string){const r=await configurationApi.testModel(type);r.success?ElMessage.success(r.message||"连接成功"):ElMessage.error(r.message||"连接失败")}
function openSetting(row:SystemSetting){settingEdit.value=row;Object.assign(settingForm,{value:String(row.value),description:row.description})}
async function saveSetting(){if(settingEdit.value)await configurationApi.saveSetting(settingEdit.value.setting_key,settingForm.value,settingForm.description);settingEdit.value=null;await load()}
</script><template><el-card class="page-card" header="模型服务与系统配置"><el-alert title="模型密钥加密保存并仅显示掩码；保存后新的问答请求立即使用最新配置。" type="info" show-icon :closable="false" class="toolbar"/><el-tabs v-model="tab"><el-tab-pane label="模型接口" name="models"><el-table :data="models"><el-table-column prop="model_type" label="类型" width="110"/><el-table-column prop="name" label="名称" width="150"/><el-table-column prop="base_url" label="接口地址" min-width="280" show-overflow-tooltip/><el-table-column prop="model_name" label="模型名" width="180"/><el-table-column prop="api_key_masked" label="密钥" width="150"/><el-table-column prop="source" label="来源" width="100"/><el-table-column label="实际生效" width="110"><template #default="s"><el-tag :type="s.row.runtime_applied?'success':'info'">{{s.row.runtime_applied?'已生效':'未生效'}}</el-tag></template></el-table-column><el-table-column prop="status" label="状态" width="90"/><el-table-column label="操作" width="150"><template #default="s"><el-button link @click="openModel(s.row)">编辑</el-button><el-button link @click="testModel(s.row.model_type)">测试</el-button></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="系统参数" name="settings"><el-table :data="settings"><el-table-column prop="setting_key" label="参数" width="230"/><el-table-column prop="description" label="说明"/><el-table-column prop="value" label="当前值" width="180"/><el-table-column prop="updated_by" label="修改人" width="140"/><el-table-column label="操作" width="90"><template #default="s"><el-button link @click="openSetting(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane></el-tabs><el-dialog :model-value="Boolean(modelEdit)" title="编辑模型配置" width="700px" @close="modelEdit=null"><el-form label-position="top"><el-form-item label="配置名称"><el-input v-model="modelForm.name"/></el-form-item><el-form-item label="Base URL"><el-input v-model="modelForm.base_url"/></el-form-item><el-form-item label="模型名"><el-input v-model="modelForm.model_name"/></el-form-item><el-form-item label="API Key"><el-input v-model="modelForm.api_key" type="password" show-password placeholder="留空表示沿用现有密钥"/></el-form-item><el-form-item label="状态"><el-input v-model="modelForm.status"/></el-form-item></el-form><template #footer><el-button @click="modelEdit=null">取消</el-button><el-button type="primary" @click="saveModel">保存</el-button></template></el-dialog><el-dialog :model-value="Boolean(settingEdit)" title="编辑系统参数" @close="settingEdit=null"><el-form label-position="top"><el-form-item label="参数值"><el-input v-model="settingForm.value"/></el-form-item><el-form-item label="说明"><el-input v-model="settingForm.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="settingEdit=null">取消</el-button><el-button type="primary" @click="saveSetting">保存</el-button></template></el-dialog></el-card></template>
